import { db } from "@workspace/db";
import { benefitPlansTable } from "@workspace/db";

// Carriers already seeded: 1=Blue Shield CA, 2=Delta Dental, 3=VSP Vision Care, 4=MetLife
// Employers: 1=Catch A Vibe, 2=BetaCorp

const plans = [
  // ── Catch A Vibe (employer 1) ──────────────────────────────────────────────
  {
    employerId: 1,
    name: "Blue Shield PPO Gold",
    type: "medical",
    carrierId: 1,
    groupNumber: "CAV-MED-001",
    planYear: "2025",
    effectiveDate: "2025-01-01",
    renewalDate: "2025-12-31",
    employeeCost: "185.00",
    employerCost: "620.00",
    deductible: "500.00",
    outOfPocketMax: "3500.00",
    description: "PPO plan with broad network access. In-network deductible $500, out-of-pocket max $3,500.",
    isActive: true,
  },
  {
    employerId: 1,
    name: "Blue Shield HMO Silver",
    type: "medical",
    carrierId: 1,
    groupNumber: "CAV-MED-002",
    planYear: "2025",
    effectiveDate: "2025-01-01",
    renewalDate: "2025-12-31",
    employeeCost: "95.00",
    employerCost: "480.00",
    deductible: "1500.00",
    outOfPocketMax: "6000.00",
    description: "HMO plan requiring PCP referrals. Lower premium option with $1,500 deductible.",
    isActive: true,
  },
  {
    employerId: 1,
    name: "Delta Dental PPO",
    type: "dental",
    carrierId: 2,
    groupNumber: "CAV-DEN-001",
    planYear: "2025",
    effectiveDate: "2025-01-01",
    renewalDate: "2025-12-31",
    employeeCost: "18.00",
    employerCost: "42.00",
    deductible: "50.00",
    outOfPocketMax: "1500.00",
    description: "Preventive 100%, Basic 80%, Major 50%. Annual maximum $1,500.",
    isActive: true,
  },
  {
    employerId: 1,
    name: "VSP Vision Basic",
    type: "vision",
    carrierId: 3,
    groupNumber: "CAV-VIS-001",
    planYear: "2025",
    effectiveDate: "2025-01-01",
    renewalDate: "2025-12-31",
    employeeCost: "6.50",
    employerCost: "8.50",
    deductible: "0.00",
    outOfPocketMax: "200.00",
    description: "Annual eye exam, $150 frame allowance, copay contact lens coverage.",
    isActive: true,
  },
  {
    employerId: 1,
    name: "MetLife Group Term Life",
    type: "life",
    carrierId: 4,
    groupNumber: "CAV-LIFE-001",
    planYear: "2025",
    effectiveDate: "2025-01-01",
    renewalDate: "2025-12-31",
    employeeCost: "0.00",
    employerCost: "12.00",
    deductible: null,
    outOfPocketMax: null,
    description: "Employer-paid group term life: 1x annual salary up to $250,000.",
    isActive: true,
  },
  {
    employerId: 1,
    name: "MetLife Short-Term Disability",
    type: "disability",
    carrierId: 4,
    groupNumber: "CAV-STD-001",
    planYear: "2025",
    effectiveDate: "2025-01-01",
    renewalDate: "2025-12-31",
    employeeCost: "8.00",
    employerCost: "22.00",
    deductible: null,
    outOfPocketMax: null,
    description: "60% of weekly salary after 7-day elimination period, up to 26 weeks.",
    isActive: true,
  },

  // ── BetaCorp (employer 2) ──────────────────────────────────────────────────
  {
    employerId: 2,
    name: "Blue Shield PPO Platinum",
    type: "medical",
    carrierId: 1,
    groupNumber: "BTC-MED-001",
    planYear: "2025",
    effectiveDate: "2025-01-01",
    renewalDate: "2025-12-31",
    employeeCost: "210.00",
    employerCost: "790.00",
    deductible: "250.00",
    outOfPocketMax: "2000.00",
    description: "Premium PPO with low deductible and rich benefits. Covers 90% after deductible.",
    isActive: true,
  },
  {
    employerId: 2,
    name: "Blue Shield HDHP + HSA",
    type: "medical",
    carrierId: 1,
    groupNumber: "BTC-MED-002",
    planYear: "2025",
    effectiveDate: "2025-01-01",
    renewalDate: "2025-12-31",
    employeeCost: "65.00",
    employerCost: "420.00",
    deductible: "2800.00",
    outOfPocketMax: "7000.00",
    description: "High-deductible health plan paired with HSA. BetaCorp contributes $500/yr to HSA.",
    isActive: true,
  },
  {
    employerId: 2,
    name: "Delta Dental Enhanced",
    type: "dental",
    carrierId: 2,
    groupNumber: "BTC-DEN-001",
    planYear: "2025",
    effectiveDate: "2025-01-01",
    renewalDate: "2025-12-31",
    employeeCost: "22.00",
    employerCost: "58.00",
    deductible: "50.00",
    outOfPocketMax: "2000.00",
    description: "Includes orthodontic coverage (50%, $1,500 lifetime). Annual max $2,000.",
    isActive: true,
  },
  {
    employerId: 2,
    name: "VSP Vision Enhanced",
    type: "vision",
    carrierId: 3,
    groupNumber: "BTC-VIS-001",
    planYear: "2025",
    effectiveDate: "2025-01-01",
    renewalDate: "2025-12-31",
    employeeCost: "8.00",
    employerCost: "12.00",
    deductible: "0.00",
    outOfPocketMax: "300.00",
    description: "Annual exam, $200 frame allowance, 2-year contact lens allowance.",
    isActive: true,
  },
  {
    employerId: 2,
    name: "MetLife Group Term Life",
    type: "life",
    carrierId: 4,
    groupNumber: "BTC-LIFE-001",
    planYear: "2025",
    effectiveDate: "2025-01-01",
    renewalDate: "2025-12-31",
    employeeCost: "0.00",
    employerCost: "18.00",
    deductible: null,
    outOfPocketMax: null,
    description: "Employer-paid group term life: 2x annual salary up to $500,000.",
    isActive: true,
  },
  {
    employerId: 2,
    name: "MetLife Long-Term Disability",
    type: "disability",
    carrierId: 4,
    groupNumber: "BTC-LTD-001",
    planYear: "2025",
    effectiveDate: "2025-01-01",
    renewalDate: "2025-12-31",
    employeeCost: "14.00",
    employerCost: "36.00",
    deductible: null,
    outOfPocketMax: null,
    description: "60% of monthly salary after 90-day elimination period, benefits to age 65.",
    isActive: true,
  },
];

async function main() {
  console.log("Seeding benefit plans...");
  const result = await db.insert(benefitPlansTable).values(plans).returning({ id: benefitPlansTable.id, name: benefitPlansTable.name, type: benefitPlansTable.type });
  console.log(`✓ Inserted ${result.length} benefit plans:`);
  for (const p of result) {
    console.log(`  [${p.id}] ${p.name} (${p.type})`);
  }
  process.exit(0);
}

main().catch((e) => { console.error(e); process.exit(1); });
